name: SSH Test

on:
  push:
    branches:
      - main

jobs:
  ssh-command:
    runs-on: ubuntu-latest

    steps:
      - name: Decode PEM key and set permissions
        run: |
          echo "${{ secrets.SSH_KEY_B64 }}" | base64 -d > key.pem
          chmod 600 key.pem

      - name: Run remote command over SSH
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "ls /"
